@server=http://localhost:4004

### CompanySet
# @name Get Salary
GET {{server}}/odata/v4/employe-info/getSalary(ID='24559803-8dc4-433b-ac0e-07b49cc99b08')

### CompanySet
# @name GetTotalEmployees
GET {{server}}/odata/v4/employe-info/getTotalEmployees(ID='6288496f-07c6-409e-9646-a3b9123d9b45')

### EmployeeSet
# @name Department Update
POST {{server}}/odata/v4/employe-info/promoteEmployee
Content-Type: application/json

{
  "employeeID": "24559803-8dc4-433b-ac0e-07b49cc99b08",
}

### CompanySet
# @name CompanySet_GETs
GET {{server}}/odata/v4/employe-info/CompanySet



### CompanySet
# @name CompanySet_POST
POST {{server}}/odata/v4/employe-info/CompanySet
Content-Type: application/json

{
  "ID": "22188143-addc-4acc-af70-3161e39d33ce",
  "Name": "Prabhu",
  "Address": "India",
  "Revenue": 25209150.15,
  "EmailID": "EmailID-22188143",
  "Phone": "e-22188143",
  "RegistrationDate": "2025-09-30",
  "Industry": "Industry-22188143",
  "Country": "India"
}


### CompanySet
# @name CompanySet_PATCH
PATCH {{server}}/odata/v4/employe-info/CompanySet/22188143-addc-4acc-af70-3161e39d33ca
Content-Type: application/json

{
  "ID": "22188143-addc-4acc-af70-3161e39d33ca",
  "Name": "Name-22188143",
  "Address": "Address-22188143",
  "Revenue": 25209150.15,
  "EmailID": "EmailID-22188143",
  "Phone": "e-22188143",
  "RegistrationDate": "2000-08-30",
  "Industry": "Industry-22188143",
  "Country": "Country-22188143",
  "Employees": [
    {
      "ID": "9372340b-074c-41f4-8e2b-adc4868e2094",
      "Name": "Name-9372340",
      "Department": "Department-9372340",
      "EmailID": "EmailID-9372340",
      "PhoneNo": "No-9372340",
      "Salary": 13543097.55,
      "DateofBirth": "2020-04-03",
      "skill": {
        "ID": "10101201-3be9-449b-8e99-123c540c9086"
      }
    },
    {
      "ID": "93723415-8da2-4d9a-88dc-5b1a776552f3",
      "Name": "Name-9372341",
      "Department": "Department-9372341",
      "EmailID": "EmailID-9372341",
      "PhoneNo": "No-9372341",
      "Salary": 5162258.56,
      "DateofBirth": "2005-04-15",
      "skill": {
        "ID": "10101201-3be9-449b-8e99-123c540c9086"
      }
    }
  ]
}


### CompanySet
# @name CompanySet_DELETE
DELETE {{server}}/odata/v4/employe-info/CompanySet/22188143-addc-4acc-af70-3161e39d33ca
Content-Type: application/json


### EmployeeSet
# @name EmployeeSet_GET
GET {{server}}/odata/v4/employe-info/EmployeeSet



### EmployeeSet
# @name EmployeeSet_POST
POST {{server}}/odata/v4/employe-info/EmployeeSet
Content-Type: application/json

{
  "ID": "9372340b-074c-41f4-8e2b-adc4868e2094",
  "Name": "Name-9372340",
  "Department": "Department-9372340",
  "EmailID": "EmailID-9372340",
  "PhoneNo": "No-9372340",
  "Salary": 13543097.55,
  "DateofBirth": "2020-04-03",
  "skill": {
    "ID": "10101201-3be9-449b-8e99-123c540c9086"
  }
}


### EmployeeSet
# @name EmployeeSet_PATCH
PATCH {{server}}/odata/v4/employe-info/EmployeeSet/9372340b-074c-41f4-8e2b-adc4868e2094
Content-Type: application/json

{
  "ID": "9372340b-074c-41f4-8e2b-adc4868e2094",
  "Name": "Name-9372340",
  "Department": "Department-9372340",
  "EmailID": "EmailID-9372340",
  "PhoneNo": "No-9372340",
  "Salary": 13543097.55,
  "DateofBirth": "2020-04-03",
  "skill": {
    "ID": "10101201-3be9-449b-8e99-123c540c9086"
  }
}


### EmployeeSet
# @name EmployeeSet_DELETE
DELETE {{server}}/odata/v4/employe-info/EmployeeSet/9372340b-074c-41f4-8e2b-adc4868e2094
Content-Type: application/json


### SkillSet
# @name SkillSet_GET
GET {{server}}/odata/v4/employe-info/SkillSet



### SkillSet
# @name SkillSet_POST
POST {{server}}/odata/v4/employe-info/SkillSet
Content-Type: application/json

{
  "ID": "10101201-3be9-449b-8e99-123c540c9086",
  "PrimarySkill": "PrimarySkill-10101201",
  "SecondarySkill": "SecondarySkill-10101201",
  "UpdatedSkill": "UpdatedSkill-10101201",
  "Certification": "Certification-10101201"
}


### SkillSet
# @name SkillSet_PATCH
PATCH {{server}}/odata/v4/employe-info/SkillSet/10101201-3be9-449b-8e99-123c540c9086
Content-Type: application/json

{
  "ID": "10101201-3be9-449b-8e99-123c540c9086",
  "PrimarySkill": "PrimarySkill-10101201",
  "SecondarySkill": "SecondarySkill-10101201",
  "UpdatedSkill": "UpdatedSkill-10101201",
  "Certification": "Certification-10101201"
}


### SkillSet
# @name SkillSet_DELETE
DELETE {{server}}/odata/v4/employe-info/SkillSet/10101201-3be9-449b-8e99-123c540c9086
Content-Type: application/json
